export const GET_PRODUCET_LOADING='GET_PRODUCET_LOADING';
export const GET_PRODUCET_SUCCESS='GET_PRODUCET_SUCCESS';
export const GET_PRODUCET_FAILED='GET_PRODUCET_FAILED';
export const ADD_PRODUCET_SUCCESS='ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCET_FAILED='ADD_PRODUCET_FAILED';
